import turtle as trtl
painter = trtl.Turtle()
painter.turtlesize(1)
painter.pencolor("orange")
painter.forward(100)
painter.right(90)
painter.forward(100)
painter.right(90)
painter.forward(100)
painter.right(90)
painter.forward(100)
painter.penup()
painter.goto(60, -40)
painter.pendown()
painter.forward(20)
painter.right(90)
painter.forward(20)
painter.right(90)
painter.forward(20)
painter.right(90)
painter.forward(20)
painter.penup()
painter.goto(40, -40)
painter.pendown()
painter.forward(20)
painter.right(90)
painter.forward(20)
painter.right(90)
painter.forward(20)
painter.right(90)
painter.forward(20)
painter.penup()
painter.goto(15, -70)
painter.pendown()
painter.left(90)
painter.forward(70)
painter.right(90)
painter.forward(20)
painter.right(90)
painter.forward(70)
painter.right(90)
painter.forward(20)
painter.penup()
painter.setheading(-135)
painter.goto(20, -100)
painter.pendown()
painter.forward(40)
painter.penup()
painter.goto (80,-100)
painter.setheading(-45)
painter.pendown()
painter.forward(40)
painter.penup()
painter.goto (1000, 1000)
wn = trtl.Screen()
wn.mainloop()